version: '3.8'

services:
  search-engine-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: search-engine-app
    #environment:
    #  - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@<external-db-host>:1521/<service-name>
    #  - SPRING_DATASOURCE_USERNAME=yourusername
    #  - SPRING_DATASOURCE_PASSWORD=yourpassword
    #  - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    ports:
      - "8080:8080"
    networks:
      - search-engine-app-network

networks:
  search-engine-app-network:
    driver: bridge